# -*- coding: utf-8 -*-
"""APLICACIÓN .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/188S6_hkJtpse2hWcP12qP5uPuepx7fS_
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import librosa
from sklearn.ensemble import IsolationForest

# 1. Configuración visual premium de la interfaz web
st.set_page_config(page_title="Predicción de Fallas IA", page_icon="🏗️", layout="wide")

# Estilos visuales personalizados mediante CSS Industrial
st.markdown("""
    <style>
    .main-title { font-size:38px !important; font-weight: bold; color: #FF4B4B; text-align: center; margin-bottom: 2px; }
    .subtitle { font-size:16px !important; text-align: center; color: #666666; margin-bottom: 25px; }
    .metric-box { background-color: #F1F3F5; padding: 15px; border-radius: 8px; border-left: 5px solid #FF4B4B; }
    </style>
""", unsafe_allow_html=True)

st.markdown('<div class="main-title">🏗️ Plataforma MIXPREDICT IA</div>', unsafe_allow_html=True)
st.markdown('<div class="subtitle">Sistema de Mantenimiento Predictivo Basado en Análisis Acústico y de Vibraciones — IFTS N° 33</div>', unsafe_allow_html=True)

# 2. Barra lateral interactiva y elegante
st.sidebar.image("https://cdn-icons-png.flaticon.com/512/2622/2622709.png", width=80)
st.sidebar.title("Panel de Control")
modulo = st.sidebar.radio("Seleccione el entorno de evaluación:", ["🔬 Módulo 1: Laboratorio (NASA IMS)", "🔊 Módulo 2: Campo (Audio de Obra)"])

# ==========================================
# MÓDULO 1: LABORATORIO (NASA IMS)
# ==========================================
if modulo == "🔬 Módulo 1: Laboratorio (NASA IMS)":
    st.header("🔬 Validación de Ecuaciones Físicas (Dataset de Vibraciones)")
    st.write("Suba un archivo de texto plano extraído del banco de pruebas de la NASA para contrastar el espectro real con la frecuencia teórica de falla.")

    archivo_nasa = st.file_uploader("📂 Arrastre o seleccione el archivo de texto (.txt) de la NASA:", type=None)

    if archivo_nasa is not None:
        col1, col2 = st.columns([1, 2])
        with col1:
            st.markdown("<div class='metric-box'><b>Parámetros Teóricos del Ensayo:</b><br>• Rotación: 2000 RPM (33.33 Hz)<br>• Muestreo: 20 kHz<br>• Frecuencia Crítica BPFO: 137.33 Hz</div>", unsafe_allow_html=True)
            st.write("")
            ejecutar_fft = st.button("🚀 Calcular Transformada de Fourier (FFT)")

        with col2:
            if ejecutar_fft:
                with st.spinner("Descomponiendo señal temporal..."):
                    # Lectura del archivo .txt subido por el usuario
                    datos_brutos = np.loadtxt(archivo_nasa, delimiter='\t')
                    senal_real = datos_brutos[:, 0] # Filtramos Rodamiento 1

                    Fs = 20000.0
                    N = len(senal_real)
                    fft_valores = np.fft.fft(senal_real)
                    fft_frecuencias = np.fft.fftfreq(N, 1.0/Fs)

                    frec_pos = fft_frecuencias[:N//2]
                    amp_pos = np.abs(fft_valores[:N//2]) * (2.0 / N)

                    # Gráfico científico de alta definición
                    fig, ax = plt.subplots(figsize=(10, 4.2))
                    ax.plot(frec_pos, amp_pos, color='#111111', alpha=0.85, label='Espectro Real Realizado')
                    ax.axvline(x=137.33, color='#FF4B4B', linestyle='--', linewidth=2, label='Falla Crítica BPFO (~137.33 Hz)')
                    ax.set_xlim(0, 500)
                    ax.set_xlabel("Frecuencia (Hz)")
                    ax.set_ylabel("Amplitud de Onda")
                    ax.grid(True, linestyle=':', alpha=0.6)
                    ax.legend(loc='upper right')
                    st.pyplot(fig)
                    st.success("🎯 Espectro generado correctamente. Verifique la coincidencia de los picos de energía.")

# ==========================================
# MÓDULO 2: CAMPO (AUDIO DE OBRA REAL)
# ==========================================
elif modulo == "🔊 Módulo 2: Campo (Audio de Obra)":
    st.header("🔊 Diagnóstico Acústico en Campo de Trabajo mediante IA")
    st.write("Cargue un archivo de audio (.wav o .mp3) grabado con el celular a pie de obra en el motor de la hormigonera.")

    archivo_audio = st.file_uploader("🎵 Seleccione archivo de sonido (.wav / .mp3):", type=["wav", "mp3"])

    if archivo_audio is not None:
        st.markdown("### 🎛 Honorario de Entrada de Audio")
        st.audio(archivo_audio, format='audio/wav')

        if st.button("🔍 Iniciar Diagnóstico Inteligente"):
            with st.spinner("Procesando espectrograma y evaluando con Isolation Forest..."):
                # Carga física del audio usando librosa de forma dinámica
                audio_datos, fs_audio = librosa.load(archivo_audio, sr=None)
                duracion = len(audio_datos) / fs_audio

                # Transformada de Fourier de Tiempo Reducido (STFT)
                stft_matriz = np.abs(librosa.stft(audio_datos, n_fft=1024, hop_length=512))

                # Modelo de Inteligencia Artificial: Isolation Forest
                caracteristicas = stft_matriz.mean(axis=0).reshape(-1, 1)
                modelo_ia = IsolationForest(contamination=0.06, random_state=42)
                predicciones = modelo_ia.fit_predict(caracteristicas)

                # Cálculo métrico del Health Score
                anomalias = np.sum(predicciones == -1)
                total = len(predicciones)
                health_score = int((1 - (anomalias / total)) * 100)

                st.markdown("### 📊 Indicadores de Salud de la Maquinaria")
                c1, c2 = st.columns([1, 2])

                with c1:
                    if health_score >= 90:
                        st.metric(label="PUNTAJE DE SALUD (HEALTH SCORE)", value=f"{health_score}%", delta="ÓPTIMO (SANO)")
                        st.success("🟢 **ESTADO VERDE**\nRodamientos estables. La firma acústica opera dentro de los límites de tolerancia.")
                    elif health_score >= 70:
                        st.metric(label="PUNTAJE DE SALUD (HEALTH SCORE)", value=f"{health_score}%", delta="ALERTA MODERADA", delta_color="inverse")
                        st.warning("🟡 **ESTADO AMARILLO**\nFalla mecánica incipiente. Se recomienda planificar mantenimiento preventivo.")
                    else:
                        st.metric(label="PUNTAJE DE SALUD (HEALTH SCORE)", value=f"{health_score}%", delta="PELIGRO CRÍTICO", delta_color="inverse")
                        st.error("🔴 **ESTADO ROJO**\n¡Peligro de rotura inminente! Detenga la operación para evitar daños estructurales.")

                with c2:
                    # Renderizado estético de la Huella Dactilar del Sonido (Espectrograma)
                    fig2, ax2 = plt.subplots(figsize=(10, 4))
                    img = ax2.imshow(librosa.amplitude_to_db(stft_matriz, ref=np.max),
                                    aspect='auto', origin='lower', cmap='inferno',
                                    extent=[0, duracion, 0, fs_audio//2])
                    ax2.set_ylim(0, 4000) # Foco en frecuencias audibles de rodamientos
                    ax2.set_xlabel("Tiempo (Segundos)")
                    ax2.set_ylabel("Frecuencia Acústica (Hz)")
                    fig2.colorbar(img, ax=ax2, label="Intensidad (dB)")
                    st.pyplot(fig2)